apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-svc-sqs-primary
  labels:
    app: worker-svc
  annotations:
    autoscaling.keda.sh/paused: "true"
spec:
  scaleTargetRef:
    name: worker-svc-burst-primary
  pollingInterval: 2
  cooldownPeriod: 180
  minReplicaCount: 0
  maxReplicaCount: 31
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 30
            - type: Pods
              value: 10
              periodSeconds: 30
          selectPolicy: Max
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-worker-sqs-aws
      metadata:
        awsRegion: ap-northeast-2
        queueURLFromEnv: SQS_QUEUE_URL
        queueLength: "1"
        activationQueueLength: "0"
        scaleOnInFlight: "true"
